# Generated by Django 4.1.7 on 2023-03-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('just_join', models.CharField(blank=True, max_length=100)),
                ('no_fluff_jobs', models.CharField(blank=True, max_length=100)),
                ('pracuj', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
