# Generated by Django 4.1.7 on 2023-03-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exp',
            options={'verbose_name_plural': 'Exp'},
        ),
    ]
