# Generated by Django 4.1.7 on 2023-03-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_exp_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('just_join', models.CharField(blank=True, default=None, max_length=100)),
                ('no_fluff_jobs', models.CharField(blank=True, default=None, max_length=100)),
                ('pracuj', models.CharField(blank=True, default=None, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('just_join', models.CharField(blank=True, default=None, max_length=100)),
                ('no_fluff_jobs', models.CharField(blank=True, default=None, max_length=100)),
                ('pracuj', models.CharField(blank=True, default=None, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tech',
            },
        ),
        migrations.AlterField(
            model_name='exp',
            name='just_join',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='exp',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='exp',
            name='no_fluff_jobs',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='exp',
            name='pracuj',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
