# Generated by Django 4.1.7 on 2023-03-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_city_tech_alter_exp_just_join_alter_exp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='techs'),
        ),
    ]
